name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build-docker-image:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -t manhnd9293/social-fe .

    - name: Login docker
      env:
        PASSWORD: ${{secrets.DOCKER_PWD}}
      run: docker login -u manhnd9293 -p "$PASSWORD"
    - name: Push to docker hub
      run: docker push manhnd9293/social-fe
